name: 'Upload Honk configuration'
description: Task to upload Honk Config on changes

inputs:
  token:
    description: 'PAT for uploading config file'
    required: true
  base_url:
    description: 'Base URL for Honk Instance'
    default: 'https://gethonk.io'


runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl --write-out '%{http_code}' \
          --silent --output /dev/null \
          -X POST  -H "X-Honk-Token:${{ inputs.token }}" \
          ${{ inputs.base_url }}/rules/upload/ \
          -F "file_uploaded=@rules.yaml" --fail
